version: "3"

services:

  nginx:
    container_name: nginx${PROJECT_NUMBER}
    build:
      context: nginx/
      dockerfile: Dockerfile
    links:
      - ckan
    ports:
      - "0.0.0.0:8881:80"
    environment:
      - TZ=${TZ}
    
  ckan:
    container_name: ckan${PROJECT_NUMBER}
    image: thepaeth/ckan-thai_gdc:ckan-${CKAN_VERSION}
    env_file:
      - .env
    environment:
      - CKAN_SITE_URL=${DEFAULT_URL}:${NGINX_PORT}
      - CKAN__DATAPUSHER__CALLBACK_URL_BASE=${DEFAULT_URL}:${NGINX_PORT}
      - CKAN_DATAPUSHER_URL=http://datapusher:${DATAPUSHER_PORT}
    links:
      - db
      - solr
      - redis
      - datapusher
    # ports:
    #   - "0.0.0.0:${CKAN_PORT}:5000"
    volumes:
      - ckan_storage:/var/lib/ckan
    
  datapusher:
    container_name: datapusher${PROJECT_NUMBER}
    build:
      context: datapusher/
    ports:
      - "${DATAPUSHER_PORT}:8800"

  db:
    container_name: db-${PROJECT_NUMBER}
    build:
      context: postgresql/
      args:
        - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    environment:
      - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=${TZ}
    volumes:
      - pg_data:/var/lib/postgresql/data
     
  solr:
    container_name: solr${PROJECT_NUMBER}
    build:
      context: solr/
      args:
        - CKAN_VERSION=${CKAN_VERSION}
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data/index
    environment:
      - TZ=${TZ}

  redis:
    container_name: redis{PROJECT_NUMBER}
    image: redis:alpine

volumes:
  ckan_storage:
  pg_data:
  solr_data:
